apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HandySnacks
  title: HandySnakcs Sample # optional, human readable component name
  description: Handysnacks Configuration Files.
  consumesApis: petstore
spec:
  type: service
  owner: ecomm
  lifecycle: production
  system: testing
